version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - EXECUTION_SERVICE_URL=http://code-execution:8000
    depends_on:
      - code-execution

  code-execution:
    build: ./code_execution_service
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G 